# In order to be able to install the NLopt package, we need to use the "beta"
# Ubntu 14.04 ("trusty") build environment. This also needs to have "sudo: required".
# (https://docs.travis-ci.com/user/trusty-ci-environment/)

# Currently, the regression test scripts can't use the Python image-comparison scripts,
# because we haven't figure out how to get numpy and pyfits installed so that the
# Python scripts can find them...

sudo: required
dist: trusty

language: cpp
compiler: gcc
os:
- linux

env:
  - OMP_NUM_THREADS=4

#python:
#  - "2.7_with_system_site_packages"

addons:
  apt:
    packages:
    - libfftw3-dev
    - libcfitsio3-dev
    - libgsl0-dev
    - libnlopt-dev
#    - python-numpy
#    - python-pyfits

# python stuff so we can run python-using scripts in regression tests
#python:
#  - 2.7
#install:
#  - pip install numpy

script: 
  - scons makeimage
  - scons imfit

# Note that the following tend to produce the usual Linux-vs-OSX output mismatches
# in the final decimal places for some of the outputs (probably due to subtle
# floating-point issues).
after_success:
  - ./do_makeimage_tests
  - ./do_imfit_tests

