# We need to specify "trusty" (Ubuntu 14.04) as the dist in order to access the NLopt package
sudo: false
dist: trusty

language: cpp
compiler: gcc
os:
- linux

addons:
  apt:
    packages:
    - libfftw3-dev
    - libcfitsio3-dev
    - libgsl0-dev
    - libnlopt-dev

#before_install:
#  - apt-get -qq update
#  - apt-get install -y libfftw3-dev
#  - apt-get install -y libnlopt-dev
script: scons --no-openmp testparser
