sudo: required
dist: precise
language: cpp

compiler: gcc
os:
- linux
addons:
  apt:
    packages:
    - libfftw3-dev
    - libcfitsio3-dev
    - libgsl0-dev

#before_install:
#  - apt-get -qq update
#  - apt-get install -y libfftw3-dev
#  - apt-get install -y libnlopt-dev
script: scons --no-nlopt --no-openmp testparser
