language: cpp
compiler: gcc
os:
- linux
addons:
  apt:
    packages:
    - fftw-dev

#before_install:
#  - apt-get -qq update
#  - apt-get install -y libfftw3-dev
#  - apt-get install -y libnlopt-dev
script: scons testparser
