# In order to be able to install the NLopt package, we need to use the "beta"
# Ubntu 14.04 ("trusty") build environment. This also needs to have "sudo: required".
# (https://docs.travis-ci.com/user/trusty-ci-environment/)

sudo: required
dist: trusty

language: cpp
compiler: gcc
os:
- linux

addons:
  apt:
    packages:
    - libfftw3-dev
    - libcfitsio3-dev
    - libgsl0-dev
    - libnlopt-dev

#before_install:
#  - apt-get -qq update
#  - apt-get install -y libfftw3-dev
#  - apt-get install -y libnlopt-dev
script: scons --no-openmp makeimage
