name: Imfit CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      
      # Steps are the individual actions for each job
      steps:
        # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
      
        # Run a set of commands using the shell
        - name: setup
        run: |
            sudo apt-get install -y scons
            sudo apt-get install -y libfftw3-dev
            sudo apt-get install -y libcfitsio3-dev
            sudo apt-get install -y libgsl-dev
            sudo apt-get install -y libnlopt-dev
            sudo apt-get install -y cxxtest
      
        - name: build-makeimage
        run: scons makeimage
      
#       - name: make
#       run: make
#      
#       - name: make test
#       run: make test

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Usually this is always needed
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
